name: 'Robot 3'
spin_rate: 1.5           # in Hertz
broadcast_rate: 0.75     # in Hertz
timeout_duration: 3.0    # in seconds
buffer_horizon: 8.0      # in seconds
behaviour_sets:
  size: 3
  behaviour_set0:
    task_id: 'wander'
    task_expected_duration: 225.0 # in seconds
    motivational_behaviour:
      threshold: 360.0
      acquiescence:
        yielding_delay: 150.0   # in seconds
        giving_up_delay: 250.0  # in seconds
      impatience:
        fast_rate: 5.0
  behaviour_set1:
    task_id: 'border_protection'
    task_expected_duration: 325.0 # in seconds
    motivational_behaviour:
      threshold: 200.0
      acquiescence:
        yielding_delay: 100.0   # in seconds
        giving_up_delay: 300.0  # in seconds
      impatience:
        fast_rate: 10.0
  behaviour_set2:
    task_id: 'report'
    task_expected_duration: 60.0 # in seconds
    motivational_behaviour:
      threshold: 50.0
      acquiescence:
        yielding_delay: 60.0   # in seconds
        giving_up_delay: 50.0  # in seconds
      impatience:
        fast_rate: 7.5
sensors:
  size: 2
  sensor0:
    message_type: 'nav_msgs/Odometry'
    topic_name: 'odom'
    timeout_duration: 2.0
    buffer_horizon: 5.0
  sensor1:
    message_type: 'sensors_msgs/PointCloud'
    topic_name: 'sonar'
    timeout_duration: 2.0
    buffer_horizon: 5.0
