name: 'Robot 2'
spin_rate: 3.0           # in Hertz
broadcast_rate: 0.5      # in Hertz
timeout_duration: 2.5    # in seconds
buffer_horizon: 10.0     # in seconds
behaviour_sets:
  size: 3
  behaviour_set0:
    task_id: 'wander'
    motivational_behaviour:
      threshold: 100.0
      acquiescence:
        yielding_delay: 2.0   # in seconds
        giving_up_delay: 50.0  # in seconds
      impatience:
        fast_rate: 10.0
  behaviour_set1:
    task_id: 'border_protection'
    motivational_behaviour:
      threshold: 300.0
      acquiescence:
        yielding_delay: 1.0   # in seconds
        giving_up_delay: 50.0  # in seconds
      impatience:
        fast_rate: 5.0
  behaviour_set2:
    task_id: 'report'
    motivational_behaviour:
      threshold: 250.0
      acquiescence:
        yielding_delay: 0.5   # in seconds
        giving_up_delay: 50.0  # in seconds
      impatience:
        fast_rate: 4.0  
sensors:
  size: 2
  sensor0:
    message_type: 'nav_msgs/Odometry'
    topic_name: 'odom'
    timeout_duration: 2.0
    buffer_horizon: 5.0
  sensor1:
    message_type: 'sensors_msgs/PointCloud'
    topic_name: 'sonar'
    timeout_duration: 2.0
    buffer_horizon: 5.0
