name: 'Robot 1'
spin_rate: 2.0           # in Hertz
broadcast_rate: 1.0      # in Hertz
timeout_duration: 2.0    # in seconds
buffer_horizon: 5.0      # in seconds
behaviour_sets:
  size: 1 # alter to 3, simplified to 2 for tests
  behaviour_set0:
    task_id: 'wander'
    motivational_behaviour:
      threshold: 150.0
      acquiescence:
        yielding_delay: 1.0    # in seconds
        giving_up_delay: 20.0  # in seconds
      impatience:
        fast_rate: 5.0
  behaviour_set1:
    task_id: 'border_protection'
    motivational_behaviour:
      threshold: 200.0
      acquiescence:
        yielding_delay: 0.5   # in seconds
        giving_up_delay: 20.0  # in seconds
      impatience:
        fast_rate: 10.0
  behaviour_set2:
    task_id: 'report'
    motivational_behaviour:
      threshold: 250.0
      acquiescence:
        yielding_delay: 1.2   # in seconds
        giving_up_delay: 20.0  # in seconds
      impatience:
        fast_rate: 3.0
