name: 'Robot 1'
broadcast_rate: 1.0    # in Hertz
timeout_duration: 20.0    # in seconds
behaviour_sets:
  size: 3
  behaviour_set0:
    task_id: 'wander'
    motivational_behaviour:
      threshold: 200.0
      acquiescence:
        yielding_delay: 1000.0   # in seconds
        giving_up_delay: 1000.0  # in seconds
      #activity_suppression:

      impatience:
        # nao da pra saber a priori, pq depende do numero de robos no sistema (o q eh desconhecido):
                #slow_rates: [2.5, 5.0, 2.0]
        fast_rate: 5.0
        # nao da pra saber a priori, pq depende do numero de robos no sistema (o q eh desconhecido):
                #reliability_durations: [1000.0 1000.0 ] # in seconds
  behaviour_set1:
    task_id: 'border_protection'
    motivational_behaviour:
      threshold: 200.0
      acquiescence:
        yielding_delay: 500.0   # in seconds
        giving_up_delay: 420.0  # in seconds
      #activity_suppression:

      impatience:
        # nao da pra saber a priori, pq depende do numero de robos no sistema (o q eh desconhecido):
                #slow_rates: [2.5, 5.0, 2.0]
        fast_rate: 10.0
        # nao da pra saber a priori, pq depende do numero de robos no sistema (o q eh desconhecido):
                #reliability_durations: [1000.0 1000.0 ] # in seconds
  behaviour_set2:
    task_id: 'report'
    motivational_behaviour:
      threshold: 200.0
      acquiescence:
        yielding_delay: 120.0   # in seconds
        giving_up_delay: 420.0  # in seconds
      #activity_suppression:

      impatience:
        # nao da pra saber a priori, pq depende do numero de robos no sistema (o q eh desconhecido):
                #slow_rates: [2.5, 5.0, 2.0]
        fast_rate: 3.0
        # nao da pra saber a priori, pq depende do numero de robos no sistema (o q eh desconhecido):
                #reliability_durations: [1000.0 1000.0 ] # in seconds
